name: Generate Demo GIF

on:
  push:
    branches: [preview]
  pull_request:
    branches: [preview]
  workflow_dispatch:

jobs:
  generate-demo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Install VHS and dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg libvips-dev
          sudo apt install -y ttyd
          go install github.com/charmbracelet/vhs@latest

      - name: Generate demo GIF
        run: |
          vhs < preview.tape

      - name: Upload demo GIF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview
          path: preview.gif

      - name: Commit and push demo GIF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add preview.gif
          git commit -m "Update demo GIF [skip ci]" || echo "No changes to commit"
          git push
